// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using OPC.MaintenanceAPI.Data;

#nullable disable

namespace OPC.MaintenanceAPI.Migrations
{
    [DbContext(typeof(OPCDbContext))]
    [Migration("20260917060000_ThemGioVaDonDuLieuHoSoBaoTri")]
    partial class ThemGioVaDonDuLieuHoSoBaoTri
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Model đầy đủ được quản lý bởi OPCDbContextModelSnapshot
        }
    }
}