// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OPC.MaintenanceAPI.Data;

#nullable disable

namespace OPC.MaintenanceAPI.Migrations
{
    [DbContext(typeof(OPCDbContext))]
    [Migration("20260820084300_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.ChiTietKeHoachBaoTri", b =>
                {
                    b.Property<int>("MaChiTietKeHoach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietKeHoach"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MaHoSoBaoTri")
                        .HasColumnType("int");

                    b.Property<int>("MaKeHoach")
                        .HasColumnType("int");

                    b.Property<int>("MaThietBi")
                        .HasColumnType("int");

                    b.Property<DateOnly>("NgayDuKienBaoTri")
                        .HasColumnType("date");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaChiTietKeHoach")
                        .HasName("PK__ChiTietK__63E158BAABC27D93");

                    b.HasIndex("MaKeHoach");

                    b.HasIndex("MaThietBi");

                    b.HasIndex(new[] { "MaHoSoBaoTri" }, "UQ__ChiTietK__9AAC00375C21B2F0")
                        .IsUnique()
                        .HasFilter("[MaHoSoBaoTri] IS NOT NULL");

                    b.ToTable("ChiTietKeHoachBaoTri", (string)null);
                });

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.ChiTietYeuCauVatTu", b =>
                {
                    b.Property<int>("MaChiTietYeuCauVatTu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietYeuCauVatTu"));

                    b.Property<int>("MaVatTu")
                        .HasColumnType("int");

                    b.Property<int>("MaYeuCauVatTu")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongYeuCau")
                        .HasColumnType("int");

                    b.HasKey("MaChiTietYeuCauVatTu")
                        .HasName("PK__ChiTietY__80836208A54A835B");

                    b.HasIndex("MaVatTu");

                    b.HasIndex("MaYeuCauVatTu");

                    b.ToTable("ChiTietYeuCauVatTu", (string)null);
                });

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.ChuKyBaoTri", b =>
                {
                    b.Property<int>("MaChuKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChuKy"));

                    b.Property<string>("LoaiThietBi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SoThangChuKyDeXuat")
                        .HasColumnType("int");

                    b.HasKey("MaChuKy")
                        .HasName("PK__ChuKyBao__35853BEEBAC88F7E");

                    b.ToTable("ChuKyBaoTri", (string)null);
                });

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.DanhMucChucNang", b =>
                {
                    b.Property<int>("MaChucNang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChucNang"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NhomChucNang")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenChucNang")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("MaChucNang")
                        .HasName("PK__DanhMucC__B26DC257D64BF628");

                    b.ToTable("DanhMucChucNang", (string)null);
                });

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.HoSoBaoTri", b =>
                {
                    b.Property<int>("MaHoSoBaoTri")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoSoBaoTri"));

                    b.Property<string>("LyDoTuChoi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MaNhanVienDuyet")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVienTao")
                        .HasColumnType("int");

                    b.Property<int?>("MaPhanCong")
                        .HasColumnType("int");

                    b.Property<int>("MaThieBi")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayDuyet")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NoiDungCongViec")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ThoiGianDuKien")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Chờ duyệt");

                    b.HasKey("MaHoSoBaoTri")
                        .HasName("PK__HoSoBaoT__9AAC003672B25F3E");

                    b.HasIndex("MaNhanVienDuyet");

                    b.HasIndex("MaNhanVienTao");

                    b.HasIndex("MaThieBi");

                    b.HasIndex(new[] { "TrangThai" }, "IX_HoSoBaoTri_TrangThai");

                    b.HasIndex(new[] { "MaPhanCong" }, "UQ__HoSoBaoT__C279D917ECC83AEB")
                        .IsUnique()
                        .HasFilter("[MaPhanCong] IS NOT NULL");

                    b.ToTable("HoSoBaoTri", (string)null);
                });

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.HoSoSuaChua", b =>
                {
                    b.Property<int>("MaHoSoSuaChua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoSoSuaChua"));

                    b.Property<string>("LyDoTuChoi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MaNhanVienDuyet")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVienTao")
                        .HasColumnType("int");

                    b.Property<int?>("MaPhanCong")
                        .HasColumnType("int");

                    b.Property<int>("MaThieBi")
                        .HasColumnType("int");

                    b.Property<string>("MoTaHuHong")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("NgayDuyet")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PhuongAnSuaChua")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Chờ duyệt");

                    b.HasKey("MaHoSoSuaChua")
                        .HasName("PK__HoSoSuaC__B9B48E5C63379B32");

                    b.HasIndex("MaNhanVienDuyet");

                    b.HasIndex("MaNhanVienTao");

                    b.HasIndex("MaThieBi");

                    b.HasIndex(new[] { "TrangThai" }, "IX_HoSoSuaChua_TrangThai");

                    b.HasIndex(new[] { "MaPhanCong" }, "UQ__HoSoSuaC__C279D91736C9DBA8")
                        .IsUnique()
                        .HasFilter("[MaPhanCong] IS NOT NULL");

                    b.ToTable("HoSoSuaChua", (string)null);
                });

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.HoSoYeuCauVatTu", b =>
                {
                    b.Property<int>("MaYeuCauVatTu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaYeuCauVatTu"));

                    b.Property<string>("LyDoTuChoi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaHoSoSuaChua")
                        .HasColumnType("int");

                    b.Property<int?>("MaNhanVienDuyet")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVienTao")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayDuyet")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Chờ duyệt");

                    b.HasKey("MaYeuCauVatTu")
                        .HasName("PK__HoSoYeuC__2BB6DC13181B181A");

                    b.HasIndex("MaNhanVienDuyet");

                    b.HasIndex("MaNhanVienTao");

                    b.HasIndex(new[] { "MaHoSoSuaChua" }, "UQ__HoSoYeuC__B9B48E5D755382F9")
                        .IsUnique();

                    b.ToTable("HoSoYeuCauVatTu", (string)null);
                });

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.KeHoachBaoTri", b =>
                {
                    b.Property<int>("MaKeHoach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKeHoach"));

                    b.Property<int>("MaChuKy")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVienLap")
                        .HasColumnType("int");

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<DateOnly>("NgayLapKeHoach")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaKeHoach")
                        .HasName("PK__KeHoachB__88C5741F6562E6B7");

                    b.HasIndex("MaChuKy");

                    b.HasIndex("MaNhanVienLap");

                    b.ToTable("KeHoachBaoTri", (string)null);
                });

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.KetQuaThucHien", b =>
                {
                    b.Property<int>("MaKetQua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKetQua"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaNhanVienGhiNhan")
                        .HasColumnType("int");

                    b.Property<int>("MaPhanCong")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayGhiNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("SoLieuGhiNhan")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("XacNhanHoanThanh")
                        .HasColumnType("bit");

                    b.HasKey("MaKetQua")
                        .HasName("PK__KetQuaTh__D5B3102AF619BDD7");

                    b.HasIndex("MaNhanVienGhiNhan");

                    b.HasIndex(new[] { "MaPhanCong" }, "UQ__KetQuaTh__C279D917DDCCA813")
                        .IsUnique();

                    b.ToTable("KetQuaThucHien", (string)null);
                });

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.LichSuPheDuyet", b =>
                {
                    b.Property<int>("MaPheDuyet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPheDuyet"));

                    b.Property<string>("LyDo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MaHoSoBaoTri")
                        .HasColumnType("int");

                    b.Property<int?>("MaHoSoSuaChua")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVienDuyet")
                        .HasColumnType("int");

                    b.Property<int?>("MaYeuCauVatTu")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDuyet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("QuyetDinh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaPheDuyet")
                        .HasName("PK__LichSuPh__D14CE0E0A31E0715");

                    b.HasIndex("MaHoSoBaoTri");

                    b.HasIndex("MaHoSoSuaChua");

                    b.HasIndex("MaYeuCauVatTu");

                    b.HasIndex(new[] { "MaNhanVienDuyet" }, "IX_LSPD_NhanVienDuyet");

                    b.ToTable("LichSuPheDuyet", (string)null);
                });

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.LichSuThietBi", b =>
                {
                    b.Property<int>("MaLichSu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichSu"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("KetQua")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MaHoSoBaoTri")
                        .HasColumnType("int");

                    b.Property<int?>("MaHoSoSuaChua")
                        .HasColumnType("int");

                    b.Property<int>("MaThietBi")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayHoanThanh")
                        .HasColumnType("datetime");

                    b.HasKey("MaLichSu")
                        .HasName("PK__LichSuTh__C443222A120ED592");

                    b.HasIndex("MaThietBi");

                    b.HasIndex(new[] { "MaHoSoBaoTri" }, "UQ__LichSuTh__9AAC0037073AB41F")
                        .IsUnique()
                        .HasFilter("[MaHoSoBaoTri] IS NOT NULL");

                    b.HasIndex(new[] { "MaHoSoSuaChua" }, "UQ__LichSuTh__B9B48E5DF745169F")
                        .IsUnique()
                        .HasFilter("[MaHoSoSuaChua] IS NOT NULL");

                    b.ToTable("LichSuThietBi", (string)null);
                });

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.NhanVien", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhanVien"));

                    b.Property<string>("ChucVu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly?>("NgayVaoLam")
                        .HasColumnType("date");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaNhanVien")
                        .HasName("PK__NhanVien__77B2CA476C4A22F7");

                    b.HasIndex(new[] { "MaNguoiDung" }, "UQ__NhanVien__C539D763184E88B4")
                        .IsUnique();

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.NhapXuatVatTu", b =>
                {
                    b.Property<int>("MaGiaoDich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGiaoDich"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LoaiGiaoDich")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("MaNhanVienGiaoDich")
                        .HasColumnType("int");

                    b.Property<int>("MaVatTu")
                        .HasColumnType("int");

                    b.Property<int?>("MaYeuCauVatTu")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayGiaoDich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaGiaoDich")
                        .HasName("PK__NhapXuat__0A2A24EBBFDD84F5");

                    b.HasIndex("MaNhanVienGiaoDich");

                    b.HasIndex("MaVatTu");

                    b.HasIndex("MaYeuCauVatTu");

                    b.ToTable("NhapXuatVatTu", (string)null);
                });

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.NhatKyHeThong", b =>
                {
                    b.Property<int>("MaNhatKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhatKy"));

                    b.Property<string>("DiaChiIp")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("DiaChiIP");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<string>("PhuongThucHttp")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("PhuongThucHTTP");

                    b.Property<string>("TenApi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TenAPI");

                    b.Property<DateTime>("ThoiGianTruyCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("MaNhatKy")
                        .HasName("PK__NhatKyHe__E42EF42E3EF352B6");

                    b.HasIndex(new[] { "MaNhanVien", "ThoiGianTruyCap" }, "IX_NhatKy_NhanVien_ThoiGian");

                    b.ToTable("NhatKyHeThong", (string)null);
                });

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.PhanCongCongViec", b =>
                {
                    b.Property<int>("MaPhanCong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhanCong"));

                    b.Property<int>("MaNhanVienPhanCong")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVienThucHien")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("NgayBatDauDuKien")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgayKetThucDuKien")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayPhanCong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaPhanCong")
                        .HasName("PK__PhanCong__C279D9162720337F");

                    b.HasIndex("MaNhanVienPhanCong");

                    b.HasIndex("MaNhanVienThucHien");

                    b.ToTable("PhanCongCongViec", (string)null);
                });

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.PhanQuyenVaiTro", b =>
                {
                    b.Property<int>("MaPhanQuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhanQuyen"));

                    b.Property<bool>("DuocDuyet")
                        .HasColumnType("bit");

                    b.Property<bool>("DuocSua")
                        .HasColumnType("bit");

                    b.Property<bool>("DuocTao")
                        .HasColumnType("bit");

                    b.Property<bool>("DuocXem")
                        .HasColumnType("bit");

                    b.Property<int>("MaChucNang")
                        .HasColumnType("int");

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.HasKey("MaPhanQuyen")
                        .HasName("PK__PhanQuye__529AB12BD82D7C83");

                    b.HasIndex("MaChucNang");

                    b.HasIndex(new[] { "MaVaiTro", "MaChucNang" }, "UQ_PhanQuyen_VaiTro_ChucNang")
                        .IsUnique();

                    b.ToTable("PhanQuyenVaiTro", (string)null);
                });

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.QuanLyNguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<DateTime?>("LanDangNhapCuoi")
                        .HasColumnType("datetime");

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("MaNguoiDung")
                        .HasName("PK__QuanLyNg__C539D76297871A08");

                    b.HasIndex("MaVaiTro");

                    b.HasIndex(new[] { "TenDangNhap" }, "UQ__QuanLyNg__55F68FC03C332257")
                        .IsUnique();

                    b.ToTable("QuanLyNguoiDung", (string)null);
                });

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.ThietBi", b =>
                {
                    b.Property<int>("MaThietBi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThietBi"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LoaiThietBi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaChuKy")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("NgayBaoTriGanNhat")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgayBaoTriTiepTheo")
                        .HasColumnType("date");

                    b.Property<DateOnly>("NgayLapDat")
                        .HasColumnType("date");

                    b.Property<int?>("SoThangDeXuat")
                        .HasColumnType("int");

                    b.Property<string>("TenThietBi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TinhTrangHienTai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ViTriLapDat")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("MaThietBi")
                        .HasName("PK__ThietBi__8AEC71F764099605");

                    b.HasIndex("MaChuKy");

                    b.HasIndex(new[] { "NgayBaoTriTiepTheo" }, "IX_ThietBi_NgayBaoTriTiepTheo");

                    b.ToTable("ThietBi", (string)null);
                });

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVaiTro"));

                    b.Property<int?>("CapDoQuyen")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("MaVaiTro")
                        .HasName("PK__VaiTro__C24C41CFA1435993");

                    b.ToTable("VaiTro", (string)null);
                });

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.VatTu", b =>
                {
                    b.Property<int>("MaVatTu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVatTu"));

                    b.Property<string>("DonViTinh")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MucTonKhoToiThieu")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongTonKho")
                        .HasColumnType("int");

                    b.Property<string>("TenVatTu")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("MaVatTu")
                        .HasName("PK__VatTu__0BD27B6A874DA6D3");

                    b.HasIndex(new[] { "SoLuongTonKho", "MucTonKhoToiThieu" }, "IX_VatTu_TonKho");

                    b.ToTable("VatTu", (string)null);
                });

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.ChiTietKeHoachBaoTri", b =>
                {
                    b.HasOne("OPC.MaintenanceAPI.Models.HoSoBaoTri", "MaHoSoBaoTriNavigation")
                        .WithOne("ChiTietKeHoachBaoTri")
                        .HasForeignKey("OPC.MaintenanceAPI.Models.ChiTietKeHoachBaoTri", "MaHoSoBaoTri")
                        .HasConstraintName("FK_ChiTietKH_HoSoBT");

                    b.HasOne("OPC.MaintenanceAPI.Models.KeHoachBaoTri", "MaKeHoachNavigation")
                        .WithMany("ChiTietKeHoachBaoTris")
                        .HasForeignKey("MaKeHoach")
                        .IsRequired()
                        .HasConstraintName("FK_ChiTietKH_KeHoach");

                    b.HasOne("OPC.MaintenanceAPI.Models.ThietBi", "MaThietBiNavigation")
                        .WithMany("ChiTietKeHoachBaoTris")
                        .HasForeignKey("MaThietBi")
                        .IsRequired()
                        .HasConstraintName("FK_ChiTietKH_ThietBi");

                    b.Navigation("MaHoSoBaoTriNavigation");

                    b.Navigation("MaKeHoachNavigation");

                    b.Navigation("MaThietBiNavigation");
                });

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.ChiTietYeuCauVatTu", b =>
                {
                    b.HasOne("OPC.MaintenanceAPI.Models.VatTu", "MaVatTuNavigation")
                        .WithMany("ChiTietYeuCauVatTus")
                        .HasForeignKey("MaVatTu")
                        .IsRequired()
                        .HasConstraintName("FK_ChiTietYCVT_VatTu");

                    b.HasOne("OPC.MaintenanceAPI.Models.HoSoYeuCauVatTu", "MaYeuCauVatTuNavigation")
                        .WithMany("ChiTietYeuCauVatTus")
                        .HasForeignKey("MaYeuCauVatTu")
                        .IsRequired()
                        .HasConstraintName("FK_ChiTietYCVT_YeuCau");

                    b.Navigation("MaVatTuNavigation");

                    b.Navigation("MaYeuCauVatTuNavigation");
                });

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.HoSoBaoTri", b =>
                {
                    b.HasOne("OPC.MaintenanceAPI.Models.NhanVien", "MaNhanVienDuyetNavigation")
                        .WithMany("HoSoBaoTriMaNhanVienDuyetNavigations")
                        .HasForeignKey("MaNhanVienDuyet")
                        .HasConstraintName("FK_HoSoBaoTri_NVDuyet");

                    b.HasOne("OPC.MaintenanceAPI.Models.NhanVien", "MaNhanVienTaoNavigation")
                        .WithMany("HoSoBaoTriMaNhanVienTaoNavigations")
                        .HasForeignKey("MaNhanVienTao")
                        .IsRequired()
                        .HasConstraintName("FK_HoSoBaoTri_NVTao");

                    b.HasOne("OPC.MaintenanceAPI.Models.PhanCongCongViec", "MaPhanCongNavigation")
                        .WithOne("HoSoBaoTri")
                        .HasForeignKey("OPC.MaintenanceAPI.Models.HoSoBaoTri", "MaPhanCong")
                        .HasConstraintName("FK_HoSoBaoTri_PhanCong");

                    b.HasOne("OPC.MaintenanceAPI.Models.ThietBi", "MaThieBiNavigation")
                        .WithMany("HoSoBaoTris")
                        .HasForeignKey("MaThieBi")
                        .IsRequired()
                        .HasConstraintName("FK_HoSoBaoTri_ThietBi");

                    b.Navigation("MaNhanVienDuyetNavigation");

                    b.Navigation("MaNhanVienTaoNavigation");

                    b.Navigation("MaPhanCongNavigation");

                    b.Navigation("MaThieBiNavigation");
                });

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.HoSoSuaChua", b =>
                {
                    b.HasOne("OPC.MaintenanceAPI.Models.NhanVien", "MaNhanVienDuyetNavigation")
                        .WithMany("HoSoSuaChuaMaNhanVienDuyetNavigations")
                        .HasForeignKey("MaNhanVienDuyet")
                        .HasConstraintName("FK_HoSoSuaChua_NVDuyet");

                    b.HasOne("OPC.MaintenanceAPI.Models.NhanVien", "MaNhanVienTaoNavigation")
                        .WithMany("HoSoSuaChuaMaNhanVienTaoNavigations")
                        .HasForeignKey("MaNhanVienTao")
                        .IsRequired()
                        .HasConstraintName("FK_HoSoSuaChua_NVTao");

                    b.HasOne("OPC.MaintenanceAPI.Models.PhanCongCongViec", "MaPhanCongNavigation")
                        .WithOne("HoSoSuaChua")
                        .HasForeignKey("OPC.MaintenanceAPI.Models.HoSoSuaChua", "MaPhanCong")
                        .HasConstraintName("FK_HoSoSuaChua_PhanCong");

                    b.HasOne("OPC.MaintenanceAPI.Models.ThietBi", "MaThieBiNavigation")
                        .WithMany("HoSoSuaChuas")
                        .HasForeignKey("MaThieBi")
                        .IsRequired()
                        .HasConstraintName("FK_HoSoSuaChua_ThietBi");

                    b.Navigation("MaNhanVienDuyetNavigation");

                    b.Navigation("MaNhanVienTaoNavigation");

                    b.Navigation("MaPhanCongNavigation");

                    b.Navigation("MaThieBiNavigation");
                });

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.HoSoYeuCauVatTu", b =>
                {
                    b.HasOne("OPC.MaintenanceAPI.Models.HoSoSuaChua", "MaHoSoSuaChuaNavigation")
                        .WithOne("HoSoYeuCauVatTu")
                        .HasForeignKey("OPC.MaintenanceAPI.Models.HoSoYeuCauVatTu", "MaHoSoSuaChua")
                        .IsRequired()
                        .HasConstraintName("FK_YeuCauVT_HoSoSC");

                    b.HasOne("OPC.MaintenanceAPI.Models.NhanVien", "MaNhanVienDuyetNavigation")
                        .WithMany("HoSoYeuCauVatTuMaNhanVienDuyetNavigations")
                        .HasForeignKey("MaNhanVienDuyet")
                        .HasConstraintName("FK_YeuCauVT_NVDuyet");

                    b.HasOne("OPC.MaintenanceAPI.Models.NhanVien", "MaNhanVienTaoNavigation")
                        .WithMany("HoSoYeuCauVatTuMaNhanVienTaoNavigations")
                        .HasForeignKey("MaNhanVienTao")
                        .IsRequired()
                        .HasConstraintName("FK_YeuCauVT_NVTao");

                    b.Navigation("MaHoSoSuaChuaNavigation");

                    b.Navigation("MaNhanVienDuyetNavigation");

                    b.Navigation("MaNhanVienTaoNavigation");
                });

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.KeHoachBaoTri", b =>
                {
                    b.HasOne("OPC.MaintenanceAPI.Models.ChuKyBaoTri", "MaChuKyNavigation")
                        .WithMany("KeHoachBaoTris")
                        .HasForeignKey("MaChuKy")
                        .IsRequired()
                        .HasConstraintName("FK_KeHoach_ChuKy");

                    b.HasOne("OPC.MaintenanceAPI.Models.NhanVien", "MaNhanVienLapNavigation")
                        .WithMany("KeHoachBaoTris")
                        .HasForeignKey("MaNhanVienLap")
                        .IsRequired()
                        .HasConstraintName("FK_KeHoach_NhanVien");

                    b.Navigation("MaChuKyNavigation");

                    b.Navigation("MaNhanVienLapNavigation");
                });

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.KetQuaThucHien", b =>
                {
                    b.HasOne("OPC.MaintenanceAPI.Models.NhanVien", "MaNhanVienGhiNhanNavigation")
                        .WithMany("KetQuaThucHiens")
                        .HasForeignKey("MaNhanVienGhiNhan")
                        .IsRequired()
                        .HasConstraintName("FK_KetQua_NhanVien");

                    b.HasOne("OPC.MaintenanceAPI.Models.PhanCongCongViec", "MaPhanCongNavigation")
                        .WithOne("KetQuaThucHien")
                        .HasForeignKey("OPC.MaintenanceAPI.Models.KetQuaThucHien", "MaPhanCong")
                        .IsRequired()
                        .HasConstraintName("FK_KetQua_PhanCong");

                    b.Navigation("MaNhanVienGhiNhanNavigation");

                    b.Navigation("MaPhanCongNavigation");
                });

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.LichSuPheDuyet", b =>
                {
                    b.HasOne("OPC.MaintenanceAPI.Models.HoSoBaoTri", "MaHoSoBaoTriNavigation")
                        .WithMany("LichSuPheDuyets")
                        .HasForeignKey("MaHoSoBaoTri")
                        .HasConstraintName("FK_LSPD_HoSoBaoTri");

                    b.HasOne("OPC.MaintenanceAPI.Models.HoSoSuaChua", "MaHoSoSuaChuaNavigation")
                        .WithMany("LichSuPheDuyets")
                        .HasForeignKey("MaHoSoSuaChua")
                        .HasConstraintName("FK_LSPD_HoSoSuaChua");

                    b.HasOne("OPC.MaintenanceAPI.Models.NhanVien", "MaNhanVienDuyetNavigation")
                        .WithMany("LichSuPheDuyets")
                        .HasForeignKey("MaNhanVienDuyet")
                        .IsRequired()
                        .HasConstraintName("FK_LSPD_NhanVien");

                    b.HasOne("OPC.MaintenanceAPI.Models.HoSoYeuCauVatTu", "MaYeuCauVatTuNavigation")
                        .WithMany("LichSuPheDuyets")
                        .HasForeignKey("MaYeuCauVatTu")
                        .HasConstraintName("FK_LSPD_YeuCauVT");

                    b.Navigation("MaHoSoBaoTriNavigation");

                    b.Navigation("MaHoSoSuaChuaNavigation");

                    b.Navigation("MaNhanVienDuyetNavigation");

                    b.Navigation("MaYeuCauVatTuNavigation");
                });

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.LichSuThietBi", b =>
                {
                    b.HasOne("OPC.MaintenanceAPI.Models.HoSoBaoTri", "MaHoSoBaoTriNavigation")
                        .WithOne("LichSuThietBi")
                        .HasForeignKey("OPC.MaintenanceAPI.Models.LichSuThietBi", "MaHoSoBaoTri")
                        .HasConstraintName("FK_LSTB_HoSoBaoTri");

                    b.HasOne("OPC.MaintenanceAPI.Models.HoSoSuaChua", "MaHoSoSuaChuaNavigation")
                        .WithOne("LichSuThietBi")
                        .HasForeignKey("OPC.MaintenanceAPI.Models.LichSuThietBi", "MaHoSoSuaChua")
                        .HasConstraintName("FK_LSTB_HoSoSuaChua");

                    b.HasOne("OPC.MaintenanceAPI.Models.ThietBi", "MaThietBiNavigation")
                        .WithMany("LichSuThietBis")
                        .HasForeignKey("MaThietBi")
                        .IsRequired()
                        .HasConstraintName("FK_LSTB_ThietBi");

                    b.Navigation("MaHoSoBaoTriNavigation");

                    b.Navigation("MaHoSoSuaChuaNavigation");

                    b.Navigation("MaThietBiNavigation");
                });

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.NhanVien", b =>
                {
                    b.HasOne("OPC.MaintenanceAPI.Models.QuanLyNguoiDung", "MaNguoiDungNavigation")
                        .WithOne("NhanVien")
                        .HasForeignKey("OPC.MaintenanceAPI.Models.NhanVien", "MaNguoiDung")
                        .IsRequired()
                        .HasConstraintName("FK_NhanVien_NguoiDung");

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.NhapXuatVatTu", b =>
                {
                    b.HasOne("OPC.MaintenanceAPI.Models.NhanVien", "MaNhanVienGiaoDichNavigation")
                        .WithMany("NhapXuatVatTus")
                        .HasForeignKey("MaNhanVienGiaoDich")
                        .IsRequired()
                        .HasConstraintName("FK_NXVT_NhanVien");

                    b.HasOne("OPC.MaintenanceAPI.Models.VatTu", "MaVatTuNavigation")
                        .WithMany("NhapXuatVatTus")
                        .HasForeignKey("MaVatTu")
                        .IsRequired()
                        .HasConstraintName("FK_NXVT_VatTu");

                    b.HasOne("OPC.MaintenanceAPI.Models.HoSoYeuCauVatTu", "MaYeuCauVatTuNavigation")
                        .WithMany("NhapXuatVatTus")
                        .HasForeignKey("MaYeuCauVatTu")
                        .HasConstraintName("FK_NXVT_YeuCauVT");

                    b.Navigation("MaNhanVienGiaoDichNavigation");

                    b.Navigation("MaVatTuNavigation");

                    b.Navigation("MaYeuCauVatTuNavigation");
                });

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.NhatKyHeThong", b =>
                {
                    b.HasOne("OPC.MaintenanceAPI.Models.NhanVien", "MaNhanVienNavigation")
                        .WithMany("NhatKyHeThongs")
                        .HasForeignKey("MaNhanVien")
                        .IsRequired()
                        .HasConstraintName("FK_NhatKy_NhanVien");

                    b.Navigation("MaNhanVienNavigation");
                });

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.PhanCongCongViec", b =>
                {
                    b.HasOne("OPC.MaintenanceAPI.Models.NhanVien", "MaNhanVienPhanCongNavigation")
                        .WithMany("PhanCongCongViecMaNhanVienPhanCongNavigations")
                        .HasForeignKey("MaNhanVienPhanCong")
                        .IsRequired()
                        .HasConstraintName("FK_PhanCong_NhanVienPhanCong");

                    b.HasOne("OPC.MaintenanceAPI.Models.NhanVien", "MaNhanVienThucHienNavigation")
                        .WithMany("PhanCongCongViecMaNhanVienThucHienNavigations")
                        .HasForeignKey("MaNhanVienThucHien")
                        .IsRequired()
                        .HasConstraintName("FK_PhanCong_NhanVienThucHien");

                    b.Navigation("MaNhanVienPhanCongNavigation");

                    b.Navigation("MaNhanVienThucHienNavigation");
                });

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.PhanQuyenVaiTro", b =>
                {
                    b.HasOne("OPC.MaintenanceAPI.Models.DanhMucChucNang", "MaChucNangNavigation")
                        .WithMany("PhanQuyenVaiTros")
                        .HasForeignKey("MaChucNang")
                        .IsRequired()
                        .HasConstraintName("FK_PhanQuyen_ChucNang");

                    b.HasOne("OPC.MaintenanceAPI.Models.VaiTro", "MaVaiTroNavigation")
                        .WithMany("PhanQuyenVaiTros")
                        .HasForeignKey("MaVaiTro")
                        .IsRequired()
                        .HasConstraintName("FK_PhanQuyen_VaiTro");

                    b.Navigation("MaChucNangNavigation");

                    b.Navigation("MaVaiTroNavigation");
                });

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.QuanLyNguoiDung", b =>
                {
                    b.HasOne("OPC.MaintenanceAPI.Models.VaiTro", "MaVaiTroNavigation")
                        .WithMany("QuanLyNguoiDungs")
                        .HasForeignKey("MaVaiTro")
                        .IsRequired()
                        .HasConstraintName("FK_QuanLyNguoiDung_VaiTro");

                    b.Navigation("MaVaiTroNavigation");
                });

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.ThietBi", b =>
                {
                    b.HasOne("OPC.MaintenanceAPI.Models.ChuKyBaoTri", "MaChuKyNavigation")
                        .WithMany("ThietBis")
                        .HasForeignKey("MaChuKy")
                        .IsRequired()
                        .HasConstraintName("FK_ThietBi_ChuKy");

                    b.Navigation("MaChuKyNavigation");
                });

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.ChuKyBaoTri", b =>
                {
                    b.Navigation("KeHoachBaoTris");

                    b.Navigation("ThietBis");
                });

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.DanhMucChucNang", b =>
                {
                    b.Navigation("PhanQuyenVaiTros");
                });

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.HoSoBaoTri", b =>
                {
                    b.Navigation("ChiTietKeHoachBaoTri");

                    b.Navigation("LichSuPheDuyets");

                    b.Navigation("LichSuThietBi");
                });

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.HoSoSuaChua", b =>
                {
                    b.Navigation("HoSoYeuCauVatTu");

                    b.Navigation("LichSuPheDuyets");

                    b.Navigation("LichSuThietBi");
                });

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.HoSoYeuCauVatTu", b =>
                {
                    b.Navigation("ChiTietYeuCauVatTus");

                    b.Navigation("LichSuPheDuyets");

                    b.Navigation("NhapXuatVatTus");
                });

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.KeHoachBaoTri", b =>
                {
                    b.Navigation("ChiTietKeHoachBaoTris");
                });

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.NhanVien", b =>
                {
                    b.Navigation("HoSoBaoTriMaNhanVienDuyetNavigations");

                    b.Navigation("HoSoBaoTriMaNhanVienTaoNavigations");

                    b.Navigation("HoSoSuaChuaMaNhanVienDuyetNavigations");

                    b.Navigation("HoSoSuaChuaMaNhanVienTaoNavigations");

                    b.Navigation("HoSoYeuCauVatTuMaNhanVienDuyetNavigations");

                    b.Navigation("HoSoYeuCauVatTuMaNhanVienTaoNavigations");

                    b.Navigation("KeHoachBaoTris");

                    b.Navigation("KetQuaThucHiens");

                    b.Navigation("LichSuPheDuyets");

                    b.Navigation("NhapXuatVatTus");

                    b.Navigation("NhatKyHeThongs");

                    b.Navigation("PhanCongCongViecMaNhanVienPhanCongNavigations");

                    b.Navigation("PhanCongCongViecMaNhanVienThucHienNavigations");
                });

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.PhanCongCongViec", b =>
                {
                    b.Navigation("HoSoBaoTri");

                    b.Navigation("HoSoSuaChua");

                    b.Navigation("KetQuaThucHien");
                });

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.QuanLyNguoiDung", b =>
                {
                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.ThietBi", b =>
                {
                    b.Navigation("ChiTietKeHoachBaoTris");

                    b.Navigation("HoSoBaoTris");

                    b.Navigation("HoSoSuaChuas");

                    b.Navigation("LichSuThietBis");
                });

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.VaiTro", b =>
                {
                    b.Navigation("PhanQuyenVaiTros");

                    b.Navigation("QuanLyNguoiDungs");
                });

            modelBuilder.Entity("OPC.MaintenanceAPI.Models.VatTu", b =>
                {
                    b.Navigation("ChiTietYeuCauVatTus");

                    b.Navigation("NhapXuatVatTus");
                });
#pragma warning restore 612, 618
        }
    }
}
